# https://travis-ci.org/djmoch/hookmeup
language: python

matrix:
  fast_finish: true

.mixins:
- &xenial-mixin
  dist: xenial
  sudo: true
  addons:
    apt:
      packages:
        - libgnutls-dev

jobs:
  include:
    - python: 3.5
    - python: 3.6
    - <<: *xenial-mixin
      python: 3.7

install:
  - pip install -U 'pytest<3.7.0' pytest-cov pytest-pylint pytest-mock python-coveralls

script:
  - python -m pytest

after_success:
  - coveralls
