# https://travis-ci.org/djmoch/hookmeup
language: python

matrix:
  fast_finish: true

.mixins:
- &xenial-mixin
  dist: xenial
  sudo: true
  addons:
    apt:
      packages:
        - libgnutls-dev

jobs:
  include:
    - python: 3.5
    - python: 3.6
    - <<: *xenial-mixin
      python: 3.7

install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox
